services:
  clipipe-web:
    restart: unless-stopped
    build:
      context: .
    environment:
      STORAGE_DIR: /app/storage
      SERVER_PORT: 8003
    volumes:
      - ./storage:/app/storage
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    networks:
      - internal
      - shared

networks:
  shared:
    external: true
  internal:
