[project]
name = "clipipe-server"
version = "0.1.0"
description = "Send and receive data using human-readable codes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "redis>=6.4.0",
]

